version: "3.9"
services:
  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=512M
      - --reserve-memory=0M
      - --check=false
      # 2 listeners: INTERNAL (for containers) and OUTSIDE (for host tools)
      - --kafka-addr
      - INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr
      - INTERNAL://redpanda:9092,OUTSIDE://localhost:19092
      - --pandaproxy-addr
      - 0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - localhost:8082
      - --schema-registry-addr
      - 0.0.0.0:8081
    ports:
      - "9092:19092"   # host -> OUTSIDE listener
      - "9644:9644"    # admin
      - "8081:8081"    # schema registry
      - "8082:8082"    # pandaproxy
    healthcheck:
      test: ["CMD", "bash", "-lc", "rpk cluster info --brokers redpanda:9092 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - redpanda-data:/var/lib/redpanda/data

  console:
    image: redpandadata/console:latest
    depends_on: [redpanda]
    environment:
      CONFIG_FILEPATH: /etc/console/config.yaml
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./console-config.yaml
        target: /etc/console/config.yaml

  ingestor:
    build: ./ingestor
    depends_on:
      redpanda:
        condition: service_healthy
    environment:
      KAFKA_BROKERS: redpanda:9092
      TOPIC: ships
      AISSTREAM_API_KEY: ${AISSTREAM_API_KEY}
      # english channel:
      BBOX_JSON: '[[[48.5, -5.5], [51.5, 2.5]]]'
      # gulf of mexico:
      # BBOX_JSON: '[[[22.0, -97.0], [30.5, -81.0]]]'
      FILTER_MESSAGE_TYPES: "PositionReport"
      RECONNECT_SECONDS: "3"
    restart: unless-stopped

  ws-api:
    build: ./ws-api
    depends_on: [redpanda]
    environment:
      KAFKA_BROKERS: redpanda:9092
      TOPIC: ships
    ports:
      - "8000:8000"
    restart: unless-stopped

# web:
#   build: ./web
#   depends_on: [ws-api]
#   environment:
#     NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL:-ws://localhost:8000/ws}
#   ports:
#     - "3000:3000"
#   restart: unless-stopped

volumes:
  redpanda-data: