name: Only build and push changed services to github container registry

on:
  push:
    branches: [ "main", "release/**" ]
    tags: [ "v*.*.*" ]
    paths:
      - "ingestor/**"
      - "ws-api/**"
      - ".github/workflows/**"
      - "docker-compose.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "ingestor/**"
      - "ws-api/**"
      - ".github/workflows/**"
      - "docker-compose.yml"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: ingestor
            context: ./ingestor
            dockerfile: ./ingestor/Dockerfile
          - service: ws-api
            context: ./ws-api
            dockerfile: ./ws-api/Dockerfile

    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Set up QEMU (for future multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-${{ matrix.service }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag
            type=ref,event=branch
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.title=${{ matrix.service }}
            org.opencontainers.image.description=${{ matrix.service }} image from ${{ github.repository }}

      - name: Build (PRs build only) & Push (main/tags)
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max